### ISSUE TITLE
What did you think about the process of writing a command?

### ISSUE THREAD

**Issue by danielbachhuber** [Nikschavan/revslider-search-replace#2]
What went well, and what could be improved? Any documentation changes you'd suggest?

**Comment by Nikschavan** [comment]
Writing a command is very simple, I recently [contributed](https://github.com/lesterchan/wp-sweep/pull/33) a command for wp-sweep plugin as well just because it's fun and easy to write commands :)

For some reason, I did not easily find the [internal API](https://wp-cli.org/docs/internal-api/) when I needed, I searched through existing commands for some of the functions and got my way out of it.

**Comment by danielbachhuber** [comment]
> For some reason, I did not easily find the internal API when I needed, I searched through existing commands for some of the functions and got my way out of it.

Good point. I've mentioned it in a couple key places ^^
